services:
  mysql:
    image: mysql:8.0
    container_name: msoop
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: careerlink1
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: msoop1
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8082:80"

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: msoop2
    restart: always
    volumes:
      - ./project:/var/www/html
    ports:
      - "83:80"

volumes:
  mysql_data:
