FROM php:8.2-apache

# Install MySQL PDO extension
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Install dependencies for Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Enable Apache mod_rewrite
RUN a2enmod rewrite
